Decrease String.fromCharCode.apply parameter length to 16 KiB
According to Chromium issue 252492, the argument count limit
for .apply in Web Workers is not 64 KiB, as for most scripts.
Due to this, decompression of files with an uncompressed
length of at least 64 KiB and more fails with

 RangeError: Maximum call stack size exceeded

in Chromium Web Workers. A suggested workaround there is to
use blocks of 16 KiB instead, which this patch implements.

Commit which introduced the bug: 15a539bd5e6c00d85a726640e95f9e7a136c1cd5
Chromium issue URI: https://code.google.com/p/chromium/issues/detail?id=252492